### ISSUE TITLE
v5.0 armor bug

### ISSUE THREAD

**Issue by brjuseg** [galaipa/SuperBuildBattle#11]
1. After the game armor not restored.
2. After every game. People got their inventory, but not equipped armor.
3. spigot 1.8.6 SBB 5.0
4. no log :)

**Comment by galaipa** [comment]
Hi! Thanks for your report, but it works in my tests. Please update to 1.8.7 and check if it works.

Thanks

**Comment by brjuseg** [comment]
i tried to update to 1.8.7 spigot one time... server could not even start :D too many errors from different plugins
