### ISSUE TITLE
Signs (5.5)

### ISSUE THREAD

**Issue by Legomix13** [galaipa/SuperBuildBattle#13]
The users can't use the signs

**Comment by galaipa** [comment]
Please follow the rules to report a bug:

1.What problem are you having?

2.When does it happen?

3.What version of Spigot/Craftbukkit do you use? And what version of SuperBuildBattle?

4.Atach your log file

Thanks

**Comment by Legomix13** [comment]
1:The players can't use the join signs

2:When use the signs

3:Spigot 1.8.7

4:Don't have any issue in the log

**Comment by galaipa** [comment]
Are you sure you created the signs correctly?

Like in this picture: https://www.spigotmc.org/attachments/cartel-png.47241/

**Comment by Legomix13** [comment]
yes, i doit

**Comment by galaipa** [comment]
Add me on skype ( galaipa) and I will help you, because the signs are working correctly.

**Comment by gogo007** [comment]
I vé thé dame problem with 7.0 nobody van use thé sign

**Comment by gogo007** [comment]
I ve the same problem with 7.0 help please
