### ISSUE TITLE
Bug Version 6.5

### ISSUE THREAD

**Issue by filipelopes200** [galaipa/SuperBuildBattle#19]
bug-when the game is over the players did not return to the lobby
they get inside the arena
 
When does it happen: at the end of the game

Version - CraftBukkit 1.8.7
Version - SuperBuildBattle 6.5

http://pastebin.com/Ku9c0Sdk

**Comment by galaipa** [comment]
What version of WorldGuard do you have? Or you don't use it?

**Comment by filipelopes200** [comment]
Version 6.0  Beta 5 
I need to use the latest version?

**Comment by galaipa** [comment]
The plugin is only tested using the latest version of WG. Update it and it should work. Please let me know if it works or not.

Thanks

**Comment by filipelopes200** [comment]
worked properly thank you and good luck with this Plugin
