### ISSUE TITLE
Bug at the end of the game

### ISSUE THREAD

**Issue by SniipergamesFR** [galaipa/SuperBuildBattle#20]
This plugin works very well but after vots, when a player has won the game, all of players are not teleported in the lobby and they stay in the winner's slot. Please help me. It do this bug on spigot and bukkit (for me). Craftbukkit 1.8.7 and spigot 1.8.7.
PS: add multi-arena support it will be very cool

**Comment by galaipa** [comment]
Any erros in the console?

**Comment by filipelopes200** [comment]
I had the same problem then updated my world guard, worked normal
