### ISSUE TITLE
Lot of bugs :)

### ISSUE THREAD

**Issue by JohOply** [galaipa/SuperBuildBattle#29]
Hi guys ! I have find some bugs in this very nice plugin ! Could you fix them please ? (if you need more informations about them, please say me)

    - When i create arenas, "setup arena" and "next arena" put block on the ground
    - We can't modify existing arenas (time for instance?)
    - Players out of game could add and remove blocks inside a game zone
    - If I use /bbadmin > "setup arena" and again /bbadmin, any block (to create game) don't work anymore
    - If I try to go out region during the game, and there is block in the middle, i m teleported into blocks, and i can't move without break blocks
    - When I restart the server ( /restart ) during a game, blocks stay here (i can remove them in next game with "clear" option), but player loses his inventory ("real" inventory is replaced with "game" inventory)
    - When it's time to vote, players are in the middle of the arena (if there is blocks, players can't move)

And there is this error in logs (i don't know exactly why, maybe in a party) http://pastebin.com/4x2ei85W

NB: I use 7.0 and Spigot 1.8.8

**Comment by JohOply** [comment]
there isn't any support, don't use this plugin

**Comment by galaipa** [comment]
Hi!
Sorry, I forgot this issue. I will read it carefully when I have time. I have been really busy.
