### ISSUE TITLE
players can`t build in the world

### ISSUE THREAD

**Issue by brjuseg** [galaipa/SuperBuildBattle#3]
Hello. Here is the problem:
1. Other players in all the worlds can`t build or eat while players in build battle game voting for the buldings and while celebrating the winner.
2. Happens all the time while voting and celebrating.
3. Spigot 1.8.6 and super build battel 4.5
4. no log file - no errors in the console. Just the way it works.

**Comment by galaipa** [comment]
Fixed! Thank you for the report

**Comment by brjuseg** [comment]
WOW. That`s the speed i like :)

**Comment by galaipa** [comment]
If the bugs are reported well I can fix them faster :D

**Comment by brjuseg** [comment]
I am a bit noobish... how can i download fixed version? Sometime later on spigot?

**Comment by galaipa** [comment]
You will have to wait a bit
