### ISSUE TITLE
SuperBuildBattle in version 1.7.2

### ISSUE THREAD

**Issue by OriginersMc** [galaipa/SuperBuildBattle#8]
Hello,

I need that plugin in Minecraft version 1.7.2. That reason are simple. I'm Originers server owner, my server is pirate (no premium) and I use plugins of servers premium. I need this plugin in 1.7.2. Thanks, and have good day.

If you have this plugin in version 1.7.2 send me a link.

**Comment by galaipa** [comment]
Hi, unfortunately I don't have a 1.7 version of the plugin. You can solve your problem installing the plugin AutoIn and Spigot 1.8. . The server will be in online-mode: true but non premium users could also play normally.

I hope this helps you

**Comment by OriginersMc** [comment]
Ok, don't problem. But, if you have any fun plugin (same SperBuildBattle) give me please. 

Could you help me create an offline server servers similar to those premium plugins. Otherwise plugins maps sands, eg SkyWars. Especially that we are missing SurvivalGames, MobArena and paintball.

If we can achieve or pass link where to find those maps, well I would appreciate.

PS: The plugin does not have any bug. Good job :D
